FROM mcr.microsoft.com/playwright

RUN npm install -g pnpm

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

RUN apt-get update && apt-get install -y \
    xvfb \
    fluxbox \
    x11vnc \
    && apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/

RUN git clone https://github.com/novnc/noVNC.git

ENV SCREEN_WIDTH 1360
ENV SCREEN_HEIGHT 1020
ENV SCREEN_DEPTH 24
ENV DISPLAY :0

EXPOSE 9900

WORKDIR /workspace/uni-drop