FROM mcr.microsoft.com/playwright

RUN npm install -g pnpm

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

RUN apt-get update && apt-get install -y \
    xvfb \
    fluxbox \
    x11vnc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/

RUN git clone https://github.com/novnc/noVNC.git

WORKDIR /workspace/uni-drop