GET http://localhost:8080

###

POST http://localhost:8080/api/heartbeat
Content-Type: application/json

{
    "ipv4": "127.0.0.1",
    "ipv6": "fe80::1",
    "peerID": "peer0"
}

###

POST http://localhost:8080/api/remove
Content-Type: application/json

###

POST http://localhost:8080/api/pin
Content-Type: application/json

{
    "peerID": "peer0"
}

###

GET http://localhost:8080/api/pin/0123
Content-Type: application/json

