GET http://localhost:8080

###

POST http://localhost:8080/api/heartbeat
Content-Type: application/json

{
    "ipv4": "127.0.0.1",
    "ipv6": "fe80::1",
    "peerID": "peer0"
}

###

GET http://localhost:8080/api/peers?ip=127.0.0.1