name: e2e

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # for debug
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: 117503445

      - run: docker compose up -d
      
      - run: docker exec uni-drop-test pnpm run playwright

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-trace
          path: ./tests/traces
          retention-days: 1