name: fc

on:
  push:
    tags:
      - "*"

jobs:
  update-peer-discovery-version:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-node
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: install serverless-devs
        run: npm install -g @serverless-devs/s

      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
        with:
          prefix: "sha-"

      # https://help.aliyun.com/document_detail/295913.html
      - name: Update fc version
        run: |
          s config add --AccountID ${{secrets.AccountID}} --AccessKeyID ${{secrets.FC_ACCESS_KEY_ID}} --AccessKeySecret ${{secrets.FC_ACCESS_KEY_SECRET}} -a default

          s cli fc-api updateFunction --region cn-hangzhou --access default --serviceName web-drop --functionName peer-discovery --customContainerConfig '{"image": "registry-vpc.cn-hangzhou.aliyuncs.com/117503445-mirror/peer-discovery:${{ steps.commit.outputs.short }}"}'